{"uuid": "a470d3da-4eeb-4e06-9a84-bb9d64b13b1f", "befores": [{"name": "xunit_setup_function_fixture_test_selenium", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/python.py\", line 567, in xunit_setup_function_fixture\n    _call_with_optional_argument(setup_function, request.function)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/python.py\", line 741, in _call_with_optional_argument\n    func()\n  File \"/Users/liyinchi/workspace/python/python-selenium/test_selenium.py\", line 98, in setup_function\n    driverInit()\n  File \"/Users/liyinchi/workspace/python/python-selenium/test_selenium.py\", line 80, in driverInit\n    driver = webdriver.Chrome(ChromeDriverManager().install(\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/webdriver_manager/chrome.py\", line 32, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/webdriver_manager/manager.py\", line 23, in _get_driver_path\n    driver_version = driver.get_version()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/webdriver_manager/driver.py\", line 41, in get_version\n    return self.get_latest_release_version()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/webdriver_manager/driver.py\", line 72, in get_latest_release_version\n    verify=self.ssl_verify\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py\", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py\", line 645, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py\", line 501, in send\n    raise ConnectionError(err, request=request)\n"}, "start": 1642926907992, "stop": 1642926913125}], "start": 1642926907992, "stop": 1642926913441}